name: preset
description: A preset for the project

on:
  workflow_call:
    inputs:
      PRINT_THIS:
        description: The string to print
        required: true
        type: string

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Print the string
        run: echo "${{ inputs.PRINT_THIS }}"